"""modifica colonna telefono alla tabella meccanico

Revision ID: 149b49ede8ea
Revises: 7c16d77c74f4
Create Date: 2026-09-21 21:54:23.092435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149b49ede8ea'
down_revision = '7c16d77c74f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.alter_column('data_fine_rapporto',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.alter_column('data_fine_rapporto',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
