"""modifica colonna telefono aggiungendo un vincolo condizionale unique alla tabella meccanico

Revision ID: 22dbdcd3458a
Revises: 149b49ede8ea
Create Date: 2026-09-21 22:45:58.214306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbdcd3458a'
down_revision = '149b49ede8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.create_index('un_solo_telefono_attivo', ['telefono'], unique=True, postgresql_where=sa.text('data_fine_rapporto IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.drop_index('un_solo_telefono_attivo', postgresql_where=sa.text('data_fine_rapporto IS NULL'))

    # ### end Alembic commands ###
