"""Aggiunge colonna cognome alla tabella meccanico

Revision ID: 4e084378731d
Revises: ac7c4ea04890
Create Date: 2026-09-21 21:42:57.343671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e084378731d'
down_revision = 'ac7c4ea04890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognome', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.drop_column('cognome')

    # ### end Alembic commands ###
