"""modifica la colonna data preventivo con server default.

Revision ID: 4ebd0eee2ed9
Revises: 22dbdcd3458a
Create Date: 2026-09-25 07:58:05.732437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebd0eee2ed9'
down_revision = '22dbdcd3458a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preventivo', schema=None) as batch_op:
        batch_op.alter_column('data_preventivo',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preventivo', schema=None) as batch_op:
        batch_op.alter_column('data_preventivo',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
