"""Aggiunge la colonna data_fine_intervento a Intervento.

Revision ID: 7626aabe0632
Revises: 4ebd0eee2ed9
Create Date: 2026-09-26 23:16:17.080619

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7626aabe0632"
down_revision = "4ebd0eee2ed9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intervento", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "data_inizio_intervento",
                sa.Date(),
                server_default=sa.text("CURRENT_DATE"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("data_fine_intervento", sa.Date(), nullable=True))
        batch_op.alter_column(
            "ore_lavorate",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            nullable=True,
        )
        batch_op.drop_column("data_intervento")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intervento", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data_intervento", sa.DATE(), autoincrement=False, nullable=False)
        )
        batch_op.alter_column(
            "ore_lavorate",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            nullable=False,
        )
        batch_op.drop_column("data_fine_intervento")
        batch_op.drop_column("data_inizio_intervento")

    # ### end Alembic commands ###
