"""Aggiunge colonna telefono alla tabella meccanico

Revision ID: 7c16d77c74f4
Revises: 4e084378731d
Create Date: 2026-09-21 21:52:39.203675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c16d77c74f4'
down_revision = '4e084378731d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
