"""Rende data emissione fattura server_default.

Revision ID: 7d545d840eb5
Revises: fbdb645a9f72
Create Date: 2026-09-28 11:50:32.937784

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d545d840eb5"
down_revision = "fbdb645a9f72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fattura", schema=None) as batch_op:
        batch_op.alter_column(
            "data_emissione",
            existing_type=sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fattura", schema=None) as batch_op:
        batch_op.alter_column(
            "data_emissione",
            existing_type=sa.DATE(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###
