"""Modifica la colonna data_inizio di storico_proprieta

Revision ID: 8818da849cf0
Revises: dc5cae65ec90
Create Date: 2026-09-08 23:41:25.418822

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8818da849cf0"
down_revision = "dc5cae65ec90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storico_proprieta_auto", schema=None) as batch_op:
        batch_op.alter_column(
            "data_inizio",
            existing_type=sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storico_proprieta_auto", schema=None) as batch_op:
        batch_op.alter_column(
            "data_inizio",
            existing_type=sa.DATE(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###
