"""Aggiunge colonne data assunzione e fine rapport alla tabella meccanico

Revision ID: ac7c4ea04890
Revises: 8818da849cf0
Create Date: 2026-09-21 21:39:57.449021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7c4ea04890'
down_revision = '8818da849cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_assunzione', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
        batch_op.add_column(sa.Column('data_fine_rapporto', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meccanico', schema=None) as batch_op:
        batch_op.drop_column('data_fine_rapporto')
        batch_op.drop_column('data_assunzione')

    # ### end Alembic commands ###
