"""id_cliente su intervento e fattura

Revision ID: d50aafafc66a
Revises: 7d545d840eb5
Create Date: 2026-09-30 01:05:29.635633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50aafafc66a'
down_revision = '7d545d840eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fattura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fattura_id_cliente_fkey'), 'cliente', ['id_cliente'], ['id'])

    with op.batch_alter_table('intervento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('intervento_id_cliente_fkey'), 'cliente', ['id_cliente'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('intervento_id_cliente_fkey'), type_='foreignkey')
        batch_op.drop_column('id_cliente')

    with op.batch_alter_table('fattura', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fattura_id_cliente_fkey'), type_='foreignkey')
        batch_op.drop_column('id_cliente')

    # ### end Alembic commands ###
