"""aggiungi data_registrazione a cliente

Revision ID: dc5cae65ec90
Revises: 
Create Date: 2026-09-07 22:09:34.764715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5cae65ec90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_registrazione', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('data_registrazione')

    # ### end Alembic commands ###
