"""Aggiunge vincolo di unicita id_preventivo(Intervento).

Revision ID: fbdb645a9f72
Revises: 7626aabe0632
Create Date: 2026-09-27 10:48:48.576825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdb645a9f72'
down_revision = '7626aabe0632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervento', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_preventivo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
