from models.auto import Auto
from models.cliente import Cliente
from models.fattura import Fattura
from models.intervento import Intervento
from models.intervento_ricambio import InterventoRicambio
from models.meccanico import Meccanico
from models.preventivo import Preventivo
from models.ricambio import Ricambio
from models.storico_proprieta_auto import StoricoProprietaAuto
